baseurl = "http://ryan.himmelwright.net"
#baseurl = ""
relativeURLs = true
publishDir = "../himmAllRight.github.io/"
title = "Î» ryan. himmelwright. net"
canonifyurls = true
paginate = 1000
theme = "ryan-clean-blog"
languageCode = "en-us"

googleAnalytics = "UA-123-45" # delete or comment to disable Google Analytics JS generation
disqusShortname = "himmallright" #delete or comment to disable Disqus comments

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[markup]
  defaultMarkdownHandler = "blackfriday"

[author]
  name = "Ryan Himmelwright"

[params]
  DateForm = "Mon, Jan 2, 2006"
  #Description = "Software Quality Engineer, Open Source and Technology Enthusiast"
  Author = "Ryan Himmelwright"
  email = "ryan@himmelwright.net"
  recent_posts_number = 10
  showReadTime = true

[params.header]
  image = "/img/default-header.jpg"
#  home_image = "atc-tower.jpeg"
   home_image = "/img/durham-eno1-header.jpeg"
  #home_caption = "American Tobacco Campus - Durham, NC"
  home_caption = "Eno River State Park, Durham, NC"

[[params.social]]
  title = "github"
  url = "https://github.com/himmAllRight"
[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/in/ryan-himmelwright-b3891774/"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200

[[menu.main]]
  name = "tags"
  url = "/tags"
  weight = -100

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -80

[[menu.main]]
  name = "RSS"
  url = "/post/index.xml"
  weight = 0
