#!/bin/sh

# name
session="Website"
BINDURL=$1

# Setup Windows
tmux new-session -d -s $session

# setup Server window
tmux new-window -t $session:0 -n 'Server'
tmux send-keys -t 'Server' "./bind-serve ${BINDURL}" C-m

# setup Writting window
tmux new-window -t $session:0 -n 'Writting'
tmux send-keys -t 'Writting' "nvim" C-m

# setup Output window
tmux new-window -t $session:0 -n 'Output'
tmux send-keys -t 'Output' "cd ../himmAllRight.github.io; zsh" C-m

# Attach session
tmux attach-session -t $session
