#!/bin/sh

# Set Session Name
session="Website"

# Start New Session with our name
tmux new-session -d -s $session


# Name first Pane and start zsh
tmux rename-window -t 0 'Main'
tmux send-keys -t 'Main' 'zsh' C-m 'clear' C-m # Switch to bind script?

# setup Writting window
tmux new-window -t $session:1 -n 'Writting'
tmux send-keys -t 'Writting' "nvim" C-m

# Create and setup pane for hugo server
tmux new-window -t $session:1 -n 'Hugo Server'
tmux send-keys -t 'Hugo Server' 'hugo serve -D -F' C-m # Switch to bind script?

# Setup an additional shell
tmux new-window -t $session:1 -n 'Shell'
tmux send-keys -t 'Shell' "zsh" C-m 'clear' C-m

# Attach Session, on the Main window
tmux attach-session -t $session:0
